# Generated by Django 3.2.6 on 2021-09-12 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('total_price', models.FloatField()),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RBApp.cart')),
            ],
        ),
        migrations.CreateModel(
            name='MenuType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('street', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_city', to='RBApp.user')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_country', to='RBApp.user')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RBApp.cartitem')),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_phone_number', to='RBApp.user')),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_username', to='RBApp.user')),
                ('total_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oder_total_price', to='RBApp.cart')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item_id', to='RBApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('dish_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=255)),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RBApp.menutype')),
            ],
        ),
        migrations.AddField(
            model_name='cartitem',
            name='dish_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RBApp.dish'),
        ),
        migrations.AddField(
            model_name='cart',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RBApp.user'),
        ),
    ]
