# Generated by Django 3.2.6 on 2021-09-14 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RBApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='image_location',
            field=models.CharField(default='', max_length=255),
        ),
    ]
