# Generated by Django 3.2.6 on 2021-09-14 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RBApp', '0002_dish_image_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='dish_id',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='image_location',
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='cart',
            name='username',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='dish',
            name='type_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='menutype',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='menutype',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='order',
            name='item_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='order',
            name='street',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='username',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='street',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='UserToOrder',
            fields=[
                ('seq_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RBApp.order')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RBApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='ItemsInCart',
            fields=[
                ('seq_id', models.AutoField(primary_key=True, serialize=False)),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RBApp.cart')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RBApp.cartitem')),
            ],
        ),
        migrations.CreateModel(
            name='DishType',
            fields=[
                ('seq_id', models.AutoField(primary_key=True, serialize=False)),
                ('dish_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RBApp.dish')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RBApp.menutype')),
            ],
        ),
        migrations.CreateModel(
            name='DishToCartItem',
            fields=[
                ('seq_id', models.AutoField(primary_key=True, serialize=False)),
                ('dish_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RBApp.dish')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RBApp.cartitem')),
            ],
        ),
        migrations.CreateModel(
            name='CartToUser',
            fields=[
                ('seq_id', models.AutoField(primary_key=True, serialize=False)),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RBApp.cart')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RBApp.user')),
            ],
        ),
    ]
