# Generated by Django 3.2.6 on 2021-09-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RBApp', '0003_auto_20210914_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='image_location',
            field=models.CharField(default='', max_length=256),
        ),
    ]
