# Generated by Django 3.2.6 on 2021-09-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RBApp', '0005_auto_20210914_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='image_location',
            field=models.CharField(default='', max_length=255),
        ),
    ]
